---

- name: Create out dir
  file:
    path: '{{ watchmap_out_dir }}'
    state: directory
    owner: '{{ watchmap_user }}'
  become: true

- name: Install watchmap
  pip:
    name: watchmap
    state: latest
  become: true
  become_user: '{{ watchmap_user }}'

- name: Push watchmap wrapper script
  template:
    src: watchmap_udev_script.sh.j2
    dest: /usr/local/bin/watchmap_udev_script.sh
    mode: "755"
  become: true

- name: Push oneshot systemd service
  template:
    src: watchmap-service.j2
    dest: /etc/systemd/system/watchmap@.service
  become: true

- name: Push udev rule
  template:
    src: watchmap-udev.rule.j2
    dest: /etc/udev/rules.d/99-watchmap.rules
  become: true
  notify: udev
